name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Create and push image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./source/Dockerfile
        push: true
        tags: henrybrooks/simbackend:latest
        
